// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TerraformStateFileStore is an autogenerated mock type for the TerraformStateFileStore type
type TerraformStateFileStore struct {
	mock.Mock
}

// DeleteTerraformState provides a mock function with given fields: ctx, deploymentID
func (_m *TerraformStateFileStore) DeleteTerraformState(ctx context.Context, deploymentID string) error {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTerraformState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadTerraformState provides a mock function with given fields: ctx, deploymentID
func (_m *TerraformStateFileStore) LoadTerraformState(ctx context.Context, deploymentID string) ([]byte, error) {
	ret := _m.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for LoadTerraformState")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, deploymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *TerraformStateFileStore) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTerraformState provides a mock function with given fields: ctx, deploymentID, stateData
func (_m *TerraformStateFileStore) SaveTerraformState(ctx context.Context, deploymentID string, stateData []byte) error {
	ret := _m.Called(ctx, deploymentID, stateData)

	if len(ret) == 0 {
		panic("no return value specified for SaveTerraformState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, deploymentID, stateData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTerraformStateFileStore creates a new instance of TerraformStateFileStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerraformStateFileStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerraformStateFileStore {
	mock := &TerraformStateFileStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
