name: Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.23'
  GOCACHE: ${{ github.workspace }}/.cache/go-build
  GOMODCACHE: ${{ github.workspace }}/.cache/go-mod
  GOPROXY: https://proxy.golang.org,direct

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        args: --timeout=5m ./cmd/... ./internal/... ./pkg/... ./tests/...

    - name: Setup Go tools
      uses: ./.github/actions/setup-tools
      with:
        tools: 'all'
        go-version: ${{ env.GO_VERSION }}

    - name: Run quality checks
      run: make qa